-   repo: https://github.com/awebdeveloper/pre-commit-imageoptim
       sha: '' # Use the sha or tag you want to point at like 0.0.1
       hooks:
       -   id: imageoptim
           additional_dependencies: ['imageoptim-cli']